"""empty message

Revision ID: 2ddb3363b9e5
Revises: 8d8cb9bac186
Create Date: 2022-04-06 03:28:22.955110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ddb3363b9e5'
down_revision = '8d8cb9bac186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screenshot', sa.Column('img', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screenshot', 'img')
    # ### end Alembic commands ###
