"""Initial migration

Revision ID: 8d8cb9bac186
Revises: 
Create Date: 2022-04-06 02:35:49.024749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d8cb9bac186'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('running_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_running_task_task_id'), 'running_task', ['task_id'], unique=True)
    op.create_table('screenshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screenshot_url'), 'screenshot', ['url'], unique=True)
    op.create_table('task_screenshot',
    sa.Column('running_task_id', sa.Integer(), nullable=True),
    sa.Column('screenshot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['running_task_id'], ['running_task.id'], ),
    sa.ForeignKeyConstraint(['screenshot_id'], ['screenshot.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_screenshot')
    op.drop_index(op.f('ix_screenshot_url'), table_name='screenshot')
    op.drop_table('screenshot')
    op.drop_index(op.f('ix_running_task_task_id'), table_name='running_task')
    op.drop_table('running_task')
    # ### end Alembic commands ###
